# Generated by Django 3.0.7 on 2021-07-14 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AutosMake',
            new_name='MakeCreate',
        ),
    ]
