# Generated by Django 3.0.7 on 2021-07-14 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autos', '0003_autoscreate'),
    ]

    operations = [
        migrations.AddField(
            model_name='autoscreate',
            name='nickname',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
