# Generated by Django 3.2.5 on 2021-07-22 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autos', '0006_alter_makecreate_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='makecreate',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
